### ISSUE TITLE
Convert Categories Vs. Tags Lesson Plan

### ISSUE THREAD

**Issue by jsmcintyre25** [wptrainingteam/categories-versus-tags#1]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [x]  clean up the Markdown
- [x]  download the old images
- [x]  upload the images into GitHub
- [x]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/user-lessons/categories-vs-tags/

**Comment by JulieKuehl** [comment]
images were not able to be recovered, they'll have to be re-created
